module.exports = [
    {
        inputs: [{ internalType: 'address', name: '_custodyAddress', type: 'address' }],
        stateMutability: 'nonpayable',
        type: 'constructor',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
            { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
        ],
        name: 'OwnershipTransferred',
        type: 'event',
    },
    {
        inputs: [{ internalType: 'address', name: '', type: 'address' }],
        name: 'STOOwners',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '', type: 'address' }],
        name: 'STOs',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'string', name: 'country', type: 'string' }],
        name: 'addCountry',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'string', name: 'industry', type: 'string' }],
        name: 'addIndustry',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        name: 'allSTOs',
        outputs: [
            { internalType: 'address', name: 'rwaToken', type: 'address' },
            { internalType: 'address', name: 'wrappedAddress', type: 'address' },
            { internalType: 'string', name: 'stoTokenName', type: 'string' },
            { internalType: 'string', name: 'stoTokenSymbol', type: 'string' },
            { internalType: 'uint256', name: 'initialSupply', type: 'uint256' },
            { internalType: 'string', name: 'stoImage', type: 'string' },
            { internalType: 'string', name: 'country', type: 'string' },
            { internalType: 'string', name: 'issuer', type: 'string' },
            { internalType: 'uint256', name: 'issuanceDate', type: 'uint256' },
            { internalType: 'string', name: 'industry', type: 'string' },
            { internalType: 'string', name: 'companyWebsite', type: 'string' },
            { internalType: 'string', name: 'description', type: 'string' },
            { internalType: 'bool', name: 'featured', type: 'bool' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'rwaToken', type: 'address' },
            { internalType: 'bool', name: 'featured', type: 'bool' },
        ],
        name: 'changeSTOFeatureStatus',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'rwaToken', type: 'address' },
            { internalType: 'string', name: 'stoTokenName', type: 'string' },
            { internalType: 'string', name: 'stoTokenSymbol', type: 'string' },
            { internalType: 'uint256', name: 'initialSupply', type: 'uint256' },
            { internalType: 'string', name: 'stoImage', type: 'string' },
            { internalType: 'string', name: 'country', type: 'string' },
            { internalType: 'string', name: 'issuer', type: 'string' },
            { internalType: 'uint256', name: 'issuanceDate', type: 'uint256' },
            { internalType: 'string', name: 'industry', type: 'string' },
            { internalType: 'string', name: 'companyWebsite', type: 'string' },
            { internalType: 'string', name: 'description', type: 'string' },
        ],
        name: 'createSTO',
        outputs: [{ internalType: 'contract WETH', name: '', type: 'address' }],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'custodyAddress',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getAllSTOs',
        outputs: [
            {
                components: [
                    { internalType: 'address', name: 'rwaToken', type: 'address' },
                    { internalType: 'address', name: 'wrappedAddress', type: 'address' },
                    { internalType: 'string', name: 'stoTokenName', type: 'string' },
                    { internalType: 'string', name: 'stoTokenSymbol', type: 'string' },
                    { internalType: 'uint256', name: 'initialSupply', type: 'uint256' },
                    { internalType: 'string', name: 'stoImage', type: 'string' },
                    { internalType: 'string', name: 'country', type: 'string' },
                    { internalType: 'string', name: 'issuer', type: 'string' },
                    { internalType: 'uint256', name: 'issuanceDate', type: 'uint256' },
                    { internalType: 'string', name: 'industry', type: 'string' },
                    { internalType: 'string', name: 'companyWebsite', type: 'string' },
                    { internalType: 'string', name: 'description', type: 'string' },
                    { internalType: 'bool', name: 'featured', type: 'bool' },
                ],
                internalType: 'struct STOFactory.STOInfo[]',
                name: '',
                type: 'tuple[]',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getFeaturedSTOs',
        outputs: [
            {
                components: [
                    { internalType: 'address', name: 'rwaToken', type: 'address' },
                    { internalType: 'address', name: 'wrappedAddress', type: 'address' },
                    { internalType: 'string', name: 'stoTokenName', type: 'string' },
                    { internalType: 'string', name: 'stoTokenSymbol', type: 'string' },
                    { internalType: 'uint256', name: 'initialSupply', type: 'uint256' },
                    { internalType: 'string', name: 'stoImage', type: 'string' },
                    { internalType: 'string', name: 'country', type: 'string' },
                    { internalType: 'string', name: 'issuer', type: 'string' },
                    { internalType: 'uint256', name: 'issuanceDate', type: 'uint256' },
                    { internalType: 'string', name: 'industry', type: 'string' },
                    { internalType: 'string', name: 'companyWebsite', type: 'string' },
                    { internalType: 'string', name: 'description', type: 'string' },
                    { internalType: 'bool', name: 'featured', type: 'bool' },
                ],
                internalType: 'struct STOFactory.STOInfo[]',
                name: '',
                type: 'tuple[]',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getSTOCount',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: 'rwaToken', type: 'address' }],
        name: 'getSTOInfo',
        outputs: [
            {
                components: [
                    { internalType: 'address', name: 'rwaToken', type: 'address' },
                    { internalType: 'address', name: 'wrappedAddress', type: 'address' },
                    { internalType: 'string', name: 'stoTokenName', type: 'string' },
                    { internalType: 'string', name: 'stoTokenSymbol', type: 'string' },
                    { internalType: 'uint256', name: 'initialSupply', type: 'uint256' },
                    { internalType: 'string', name: 'stoImage', type: 'string' },
                    { internalType: 'string', name: 'country', type: 'string' },
                    { internalType: 'string', name: 'issuer', type: 'string' },
                    { internalType: 'uint256', name: 'issuanceDate', type: 'uint256' },
                    { internalType: 'string', name: 'industry', type: 'string' },
                    { internalType: 'string', name: 'companyWebsite', type: 'string' },
                    { internalType: 'string', name: 'description', type: 'string' },
                    { internalType: 'bool', name: 'featured', type: 'bool' },
                ],
                internalType: 'struct STOFactory.STOInfo',
                name: '',
                type: 'tuple',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
        name: 'getSTOsByOwner',
        outputs: [
            {
                components: [
                    { internalType: 'address', name: 'rwaToken', type: 'address' },
                    { internalType: 'address', name: 'wrappedAddress', type: 'address' },
                    { internalType: 'string', name: 'stoTokenName', type: 'string' },
                    { internalType: 'string', name: 'stoTokenSymbol', type: 'string' },
                    { internalType: 'uint256', name: 'initialSupply', type: 'uint256' },
                    { internalType: 'string', name: 'stoImage', type: 'string' },
                    { internalType: 'string', name: 'country', type: 'string' },
                    { internalType: 'string', name: 'issuer', type: 'string' },
                    { internalType: 'uint256', name: 'issuanceDate', type: 'uint256' },
                    { internalType: 'string', name: 'industry', type: 'string' },
                    { internalType: 'string', name: 'companyWebsite', type: 'string' },
                    { internalType: 'string', name: 'description', type: 'string' },
                    { internalType: 'bool', name: 'featured', type: 'bool' },
                ],
                internalType: 'struct STOFactory.STOInfo[]',
                name: '',
                type: 'tuple[]',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getValidCountries',
        outputs: [{ internalType: 'string[]', name: '', type: 'string[]' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getValidIndustries',
        outputs: [{ internalType: 'string[]', name: '', type: 'string[]' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'string', name: 'country', type: 'string' }],
        name: 'isValidCountry',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'string', name: 'industry', type: 'string' }],
        name: 'isValidIndustry',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'owner',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    { inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
        inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
        name: 'transferOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        name: 'validCountries',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        name: 'validIndustries',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
];
